import os
import json
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable

def generate_executive_dossier_pdf(candidate_data: dict, ai_eval_data: dict) -> bytes:
    """
    Generates a crisp Executive Candidate Snapshot & AI Dossier Brief PDF.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()

    # Custom Color Palette (RIS Navy, Gold, Emerald)
    NAVY = colors.HexColor('#002147')
    GOLD = colors.HexColor('#d97706')
    DARK_BG = colors.HexColor('#061121')
    LIGHT_BG = colors.HexColor('#f8fafc')
    ACCENT_GREEN = colors.HexColor('#059669')

    # Custom Paragraph Styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=NAVY
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=14,
        textColor=GOLD
    )
    h2_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=NAVY,
        spaceBefore=10,
        spaceAfter=6
    )
    body_style = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#1e293b')
    )
    bold_body = ParagraphStyle(
        'BoldBody',
        parent=body_style,
        fontName='Helvetica-Bold'
    )
    tag_style = ParagraphStyle(
        'TagText',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor('#002147')
    )

    story = []

    # 1. Header Banner
    header_data = [
        [
            Paragraph("<b>RIS EXECUTIVE SELECTION BRIEF</b><br/><font size=8 color='#64748b'>Research and Information System for Developing Countries</font>", title_style),
            Paragraph("<b>CONFIDENTIAL DOSSIER</b><br/><font size=8 color='#d97706'>Generated by AI Selection Crew</font>", subtitle_style)
        ]
    ]
    header_table = Table(header_data, colWidths=[380, 160])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('ALIGN', (1,0), (1,0), 'RIGHT'),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=2, color=NAVY, spaceAfter=12))

    # 2. Candidate Persona Header Block
    c_name = candidate_data.get("full_name", "Applicant")
    c_email = candidate_data.get("email", "N/A")
    c_mobile = f"{candidate_data.get('country_code', '')} {candidate_data.get('mobile_no', '')}".strip()
    c_exp = f"{candidate_data.get('years_of_experience', 0)} Years"
    c_location = f"{candidate_data.get('city', '')}, {candidate_data.get('state', '')}".strip(', ')

    meta_data = [
        [
            Paragraph(f"<b>Candidate:</b> {c_name}", bold_body),
            Paragraph(f"<b>Email:</b> {c_email}", body_style),
            Paragraph(f"<b>Experience:</b> {c_exp}", body_style)
        ],
        [
            Paragraph(f"<b>Location:</b> {c_location}", body_style),
            Paragraph(f"<b>Mobile:</b> {c_mobile}", body_style),
            Paragraph(f"<b>Highest Edu:</b> {candidate_data.get('graduation', [{}])[0].get('degree_name', 'Graduate') if candidate_data.get('graduation') else 'Graduate'}", body_style)
        ]
    ]
    meta_table = Table(meta_data, colWidths=[180, 180, 180])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_BG),
        ('PADDING', (0,0), (-1,-1), 8),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 12))

    # 3. Qualitative Selection Brief Block (From AI Evaluation)
    if ai_eval_data:
        alignment = ai_eval_data.get("semantic_alignment", "High Alignment")
        ai_class = ai_eval_data.get("ai_detector", {}).get("ai_classification", "Likely Human Writing")
        tags = ai_eval_data.get("matched_skill_tags", ["Policy Analysis", "Research"])
        strengths = ai_eval_data.get("key_strengths", [])
        questions = ai_eval_data.get("tailored_interview_questions", [])

        # Executive Summary Box
        ai_box_data = [
            [
                Paragraph(f"<b>🎯 Semantic Alignment:</b> {alignment}", ParagraphStyle('A1', parent=bold_body, textColor=GOLD)),
                Paragraph(f"<b>🔍 SOP Authenticity:</b> {ai_class}", ParagraphStyle('A2', parent=bold_body, textColor=ACCENT_GREEN))
            ]
        ]
        ai_box_table = Table(ai_box_data, colWidths=[270, 270])
        ai_box_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#061121')),
            ('TEXTCOLOR', (0,0), (-1,-1), colors.white),
            ('PADDING', (0,0), (-1,-1), 10),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story.append(ai_box_table)
        story.append(Spacer(1, 10))

        # Matched Skill Tags
        story.append(Paragraph("<b>🏷️ Matched Domain & Skill Tags:</b>", h2_style))
        tag_items = [Paragraph(f"<b>#{t}</b>", tag_style) for t in tags[:6]]
        if tag_items:
            tag_table = Table([tag_items], colWidths=[90]*len(tag_items))
            tag_table.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#e0f2fe')),
                ('PADDING', (0,0), (-1,-1), 4),
                ('ALIGN', (0,0), (-1,-1), 'CENTER'),
                ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#7dd3fc')),
            ]))
            story.append(tag_table)
            story.append(Spacer(1, 10))

        # Strengths & Questions Grid
        sq_data = []
        col_s = "<b>🌟 Key Profile Highlights:</b><br/>" + "<br/>".join([f"• {s}" for s in strengths]) if strengths else "N/A"
        col_q = "<b>❓ Tailored Interview Questions:</b><br/>" + "<br/>".join([f"{i+1}. {q}" for i, q in enumerate(questions)]) if questions else "N/A"

        sq_table = Table([[Paragraph(col_s, body_style), Paragraph(col_q, body_style)]], colWidths=[265, 275])
        sq_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (0,0), colors.HexColor('#f0fdf4')),
            ('BACKGROUND', (1,0), (1,0), colors.HexColor('#fffbeb')),
            ('PADDING', (0,0), (-1,-1), 10),
            ('BOX', (0,0), (0,0), 0.5, colors.HexColor('#bbf7d0')),
            ('BOX', (1,0), (1,0), 0.5, colors.HexColor('#fde68a')),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ]))
        story.append(sq_table)
        story.append(Spacer(1, 12))

    # 4. Statement of Purpose (SOP) Excerpt
    sop_text = candidate_data.get("sop")
    if sop_text:
        story.append(Paragraph("<b>📝 Statement of Purpose (SOP):</b>", h2_style))
        sop_p = Paragraph(f"<i>\"{sop_text[:800]}{'...' if len(sop_text) > 800 else ''}\"</i>", body_style)
        sop_table = Table([[sop_p]], colWidths=[540])
        sop_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), LIGHT_BG),
            ('PADDING', (0,0), (-1,-1), 8),
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ]))
        story.append(sop_table)
        story.append(Spacer(1, 12))

    # 5. Footer Notice
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#cbd5e1'), spaceAfter=8))
    story.append(Paragraph("<font size=7 color='#64748b'>Official Executive Dossier Snapshot · RIS Career Portal · Confidential Document</font>", body_style))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
